<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('continents')->delete();
        DB::table('continents')->insert([
            ['code' => 'AF', 'name' => 'Africa'],
            ['code' => 'AS', 'name' => 'Asia'],
            ['code' => 'EU', 'name' => 'Europe'],
            ['code' => 'NA', 'name' => 'North America'],
            ['code' => 'SA', 'name' => 'South America'],
            ['code' => 'OC', 'name' => 'Oceania'],
            ['code' => 'AN', 'name' => 'Antarctica'],
        ]);

        $countries = [
            [
                "id" => 1,
                "code" => "AF",
                "continent_code" => "AS",
                "name" => "Afghanistan",
                "iso3" => "AFG",
                "number" => "004",
                "full_name" => "Islamic Republic of Afghanistan",
                "flag" => "AF.png",
                "continent_id" => 2,
            ],
            [
                "id" => 2,
                "code" => "AX",
                "continent_code" => "EU",
                "name" => "Åland Islands",
                "iso3" => "ALA",
                "number" => "248",
                "full_name" => "Åland Islands",
                "flag" => "AX.png",
                "continent_id" => 3,
            ],
            [
                "id" => 3,
                "code" => "AL",
                "continent_code" => "EU",
                "name" => "Albania",
                "iso3" => "ALB",
                "number" => "008",
                "full_name" => "Republic of Albania",
                "flag" => "AL.png",
                "continent_id" => 3,
            ],
            [
                "id" => 4,
                "code" => "DZ",
                "continent_code" => "AF",
                "name" => "Algeria",
                "iso3" => "DZA",
                "number" => "012",
                "full_name" => "People\\\'s Democratic Republic of Algeria",
                "flag" => "DZ.png",
                "continent_id" => 1,
            ],
            [
                "id" => 5,
                "code" => "AS",
                "continent_code" => "OC",
                "name" => "American Samoa",
                "iso3" => "ASM",
                "number" => "016",
                "full_name" => "American Samoa",
                "flag" => "AS.png",
                "continent_id" => 6,
            ],
            [
                "id" => 6,
                "code" => "AD",
                "continent_code" => "EU",
                "name" => "Andorra",
                "iso3" => "AND",
                "number" => "020",
                "full_name" => "Principality of Andorra",
                "flag" => "AD.png",
                "continent_id" => 3,
            ],
            [
                "id" => 7,
                "code" => "AO",
                "continent_code" => "AF",
                "name" => "Angola",
                "iso3" => "AGO",
                "number" => "024",
                "full_name" => "Republic of Angola",
                "flag" => "AO.png",
                "continent_id" => 1,
            ],
            [
                "id" => 8,
                "code" => "AI",
                "continent_code" => "NA",
                "name" => "Anguilla",
                "iso3" => "AIA",
                "number" => "660",
                "full_name" => "Anguilla",
                "flag" => "AI.png",
                "continent_id" => 4,
            ],
            [
                "id" => 9,
                "code" => "AQ",
                "continent_code" => "AN",
                "name" => "Antarctica",
                "iso3" => "ATA",
                "number" => "010",
                "full_name" => "Antarctica (the territory South of 60 deg S)",
                "flag" => "AQ.png",
                "continent_id" => 7,
            ],
            [
                "id" => 10,
                "code" => "AG",
                "continent_code" => "NA",
                "name" => "Antigua and Barbuda",
                "iso3" => "ATG",
                "number" => "028",
                "full_name" => "Antigua and Barbuda",
                "flag" => "AG.png",
                "continent_id" => 4,
            ],
            [
                "id" => 11,
                "code" => "AR",
                "continent_code" => "SA",
                "name" => "Argentina",
                "iso3" => "ARG",
                "number" => "032",
                "full_name" => "Argentine Republic",
                "flag" => "AR.png",
                "continent_id" => 5,
            ],
            [
                "id" => 12,
                "code" => "AM",
                "continent_code" => "AS",
                "name" => "Armenia",
                "iso3" => "ARM",
                "number" => "051",
                "full_name" => "Republic of Armenia",
                "flag" => "AM.png",
                "continent_id" => 2,
            ],
            [
                "id" => 13,
                "code" => "AW",
                "continent_code" => "NA",
                "name" => "Aruba",
                "iso3" => "ABW",
                "number" => "533",
                "full_name" => "Aruba",
                "flag" => "AW.png",
                "continent_id" => 4,
            ],
            [
                "id" => 14,
                "code" => "AU",
                "continent_code" => "OC",
                "name" => "Australia",
                "iso3" => "AUS",
                "number" => "036",
                "full_name" => "Commonwealth of Australia",
                "flag" => "AU.png",
                "continent_id" => 6,
            ],
            [
                "id" => 15,
                "code" => "AT",
                "continent_code" => "EU",
                "name" => "Austria",
                "iso3" => "AUT",
                "number" => "040",
                "full_name" => "Republic of Austria",
                "flag" => "AT.png",
                "continent_id" => 3,
            ],
            [
                "id" => 16,
                "code" => "AZ",
                "continent_code" => "AS",
                "name" => "Azerbaijan",
                "iso3" => "AZE",
                "number" => "031",
                "full_name" => "Republic of Azerbaijan",
                "flag" => "AZ.png",
                "continent_id" => 2,
            ],
            [
                "id" => 17,
                "code" => "BS",
                "continent_code" => "NA",
                "name" => "Bahamas",
                "iso3" => "BHS",
                "number" => "044",
                "full_name" => "Commonwealth of the Bahamas",
                "flag" => "BS.png",
                "continent_id" => 4,
            ],
            [
                "id" => 18,
                "code" => "BH",
                "continent_code" => "AS",
                "name" => "Bahrain",
                "iso3" => "BHR",
                "number" => "048",
                "full_name" => "Kingdom of Bahrain",
                "flag" => "BH.png",
                "continent_id" => 2,
            ],
            [
                "id" => 19,
                "code" => "BD",
                "continent_code" => "AS",
                "name" => "Bangladesh",
                "iso3" => "BGD",
                "number" => "050",
                "full_name" => "People\\\'s Republic of Bangladesh",
                "flag" => "BD.png",
                "continent_id" => 2,
            ],
            [
                "id" => 20,
                "code" => "BB",
                "continent_code" => "NA",
                "name" => "Barbados",
                "iso3" => "BRB",
                "number" => "052",
                "full_name" => "Barbados",
                "flag" => "BB.png",
                "continent_id" => 4,
            ],
            [
                "id" => 21,
                "code" => "BY",
                "continent_code" => "EU",
                "name" => "Belarus",
                "iso3" => "BLR",
                "number" => "112",
                "full_name" => "Republic of Belarus",
                "flag" => "BY.png",
                "continent_id" => 3,
            ],
            [
                "id" => 22,
                "code" => "BE",
                "continent_code" => "EU",
                "name" => "Belgium",
                "iso3" => "BEL",
                "number" => "056",
                "full_name" => "Kingdom of Belgium",
                "flag" => "BE.png",
                "continent_id" => 3,
            ],
            [
                "id" => 23,
                "code" => "BZ",
                "continent_code" => "NA",
                "name" => "Belize",
                "iso3" => "BLZ",
                "number" => "084",
                "full_name" => "Belize",
                "flag" => "BZ.png",
                "continent_id" => 4,
            ],
            [
                "id" => 24,
                "code" => "BJ",
                "continent_code" => "AF",
                "name" => "Benin",
                "iso3" => "BEN",
                "number" => "204",
                "full_name" => "Republic of Benin",
                "flag" => "BJ.png",
                "continent_id" => 1,
            ],
            [
                "id" => 25,
                "code" => "BM",
                "continent_code" => "NA",
                "name" => "Bermuda",
                "iso3" => "BMU",
                "number" => "060",
                "full_name" => "Bermuda",
                "flag" => "BM.png",
                "continent_id" => 4,
            ],
            [
                "id" => 26,
                "code" => "BT",
                "continent_code" => "AS",
                "name" => "Bhutan",
                "iso3" => "BTN",
                "number" => "064",
                "full_name" => "Kingdom of Bhutan",
                "flag" => "BT.png",
                "continent_id" => 2,
            ],
            [
                "id" => 27,
                "code" => "BO",
                "continent_code" => "SA",
                "name" => "Bolivia",
                "iso3" => "BOL",
                "number" => "068",
                "full_name" => "Plurinational State of Bolivia",
                "flag" => "BO.png",
                "continent_id" => 5,
            ],
            [
                "id" => 28,
                "code" => "BQ",
                "continent_code" => "NA",
                "name" => "Bonaire, Sint Eustatius and Saba",
                "iso3" => "BES",
                "number" => "535",
                "full_name" => "Bonaire, Sint Eustatius and Saba",
                "flag" => "BQ.png",
                "continent_id" => 4,
            ],
            [
                "id" => 29,
                "code" => "BA",
                "continent_code" => "EU",
                "name" => "Bosnia and Herzegovina",
                "iso3" => "BIH",
                "number" => "070",
                "full_name" => "Bosnia and Herzegovina",
                "flag" => "BA.png",
                "continent_id" => 3,
            ],
            [
                "id" => 30,
                "code" => "BW",
                "continent_code" => "AF",
                "name" => "Botswana",
                "iso3" => "BWA",
                "number" => "072",
                "full_name" => "Republic of Botswana",
                "flag" => "BW.png",
                "continent_id" => 1,
            ],
            [
                "id" => 31,
                "code" => "BV",
                "continent_code" => "AN",
                "name" => "Bouvet Island (Bouvetøya)",
                "iso3" => "BVT",
                "number" => "074",
                "full_name" => "Bouvet Island (Bouvetøya)",
                "flag" => "BV.png",
                "continent_id" => 7,
            ],
            [
                "id" => 32,
                "code" => "BR",
                "continent_code" => "SA",
                "name" => "Brazil",
                "iso3" => "BRA",
                "number" => "076",
                "full_name" => "Federative Republic of Brazil",
                "flag" => "BR.png",
                "continent_id" => 5,
            ],
            [
                "id" => 33,
                "code" => "IO",
                "continent_code" => "AS",
                "name" => "British Indian Ocean Territory (Chagos Archipelago)",
                "iso3" => "IOT",
                "number" => "086",
                "full_name" => "British Indian Ocean Territory (Chagos Archipelago)",
                "flag" => "IO.png",
                "continent_id" => 2,
            ],
            [
                "id" => 34,
                "code" => "VG",
                "continent_code" => "NA",
                "name" => "British Virgin Islands",
                "iso3" => "VGB",
                "number" => "092",
                "full_name" => "British Virgin Islands",
                "flag" => "VG.png",
                "continent_id" => 4,
            ],
            [
                "id" => 35,
                "code" => "BN",
                "continent_code" => "AS",
                "name" => "Brunei Darussalam",
                "iso3" => "BRN",
                "number" => "096",
                "full_name" => "Brunei Darussalam",
                "flag" => "BN.png",
                "continent_id" => 2,
            ],
            [
                "id" => 36,
                "code" => "BG",
                "continent_code" => "EU",
                "name" => "Bulgaria",
                "iso3" => "BGR",
                "number" => "100",
                "full_name" => "Republic of Bulgaria",
                "flag" => "BG.png",
                "continent_id" => 3,
            ],
            [
                "id" => 37,
                "code" => "BF",
                "continent_code" => "AF",
                "name" => "Burkina Faso",
                "iso3" => "BFA",
                "number" => "854",
                "full_name" => "Burkina Faso",
                "flag" => "BF.png",
                "continent_id" => 1,
            ],
            [
                "id" => 38,
                "code" => "BI",
                "continent_code" => "AF",
                "name" => "Burundi",
                "iso3" => "BDI",
                "number" => "108",
                "full_name" => "Republic of Burundi",
                "flag" => "BI.png",
                "continent_id" => 1,
            ],
            [
                "id" => 39,
                "code" => "KH",
                "continent_code" => "AS",
                "name" => "Cambodia",
                "iso3" => "KHM",
                "number" => "116",
                "full_name" => "Kingdom of Cambodia",
                "flag" => "KH.png",
                "continent_id" => 2,
            ],
            [
                "id" => 40,
                "code" => "CM",
                "continent_code" => "AF",
                "name" => "Cameroon",
                "iso3" => "CMR",
                "number" => "120",
                "full_name" => "Republic of Cameroon",
                "flag" => "CM.png",
                "continent_id" => 1,
            ],
            [
                "id" => 41,
                "code" => "CA",
                "continent_code" => "NA",
                "name" => "Canada",
                "iso3" => "CAN",
                "number" => "124",
                "full_name" => "Canada",
                "flag" => "CA.png",
                "continent_id" => 4,
            ],
            [
                "id" => 42,
                "code" => "CV",
                "continent_code" => "AF",
                "name" => "Cabo Verde",
                "iso3" => "CPV",
                "number" => "132",
                "full_name" => "Republic of Cabo Verde",
                "flag" => "CV.png",
                "continent_id" => 1,
            ],
            [
                "id" => 43,
                "code" => "KY",
                "continent_code" => "NA",
                "name" => "Cayman Islands",
                "iso3" => "CYM",
                "number" => "136",
                "full_name" => "Cayman Islands",
                "flag" => "KY.png",
                "continent_id" => 4,
            ],
            [
                "id" => 44,
                "code" => "CF",
                "continent_code" => "AF",
                "name" => "Central African Republic",
                "iso3" => "CAF",
                "number" => "140",
                "full_name" => "Central African Republic",
                "flag" => "CF.png",
                "continent_id" => 1,
            ],
            [
                "id" => 45,
                "code" => "TD",
                "continent_code" => "AF",
                "name" => "Chad",
                "iso3" => "TCD",
                "number" => "148",
                "full_name" => "Republic of Chad",
                "flag" => "TD.png",
                "continent_id" => 1,
            ],
            [
                "id" => 46,
                "code" => "CL",
                "continent_code" => "SA",
                "name" => "Chile",
                "iso3" => "CHL",
                "number" => "152",
                "full_name" => "Republic of Chile",
                "flag" => "CL.png",
                "continent_id" => 5,
            ],
            [
                "id" => 47,
                "code" => "CN",
                "continent_code" => "AS",
                "name" => "China",
                "iso3" => "CHN",
                "number" => "156",
                "full_name" => "People\\\'s Republic of China",
                "flag" => "CN.png",
                "continent_id" => 2,
            ],
            [
                "id" => 48,
                "code" => "CX",
                "continent_code" => "AS",
                "name" => "Christmas Island",
                "iso3" => "CXR",
                "number" => "162",
                "full_name" => "Christmas Island",
                "flag" => "CX.png",
                "continent_id" => 2,
            ],
            [
                "id" => 49,
                "code" => "CC",
                "continent_code" => "AS",
                "name" => "Cocos (Keeling) Islands",
                "iso3" => "CCK",
                "number" => "166",
                "full_name" => "Cocos (Keeling) Islands",
                "flag" => "CC.png",
                "continent_id" => 2,
            ],
            [
                "id" => 50,
                "code" => "CO",
                "continent_code" => "SA",
                "name" => "Colombia",
                "iso3" => "COL",
                "number" => "170",
                "full_name" => "Republic of Colombia",
                "flag" => "CO.png",
                "continent_id" => 5,
            ],
            [
                "id" => 51,
                "code" => "KM",
                "continent_code" => "AF",
                "name" => "Comoros",
                "iso3" => "COM",
                "number" => "174",
                "full_name" => "Union of the Comoros",
                "flag" => "KM.png",
                "continent_id" => 1,
            ],
            [
                "id" => 52,
                "code" => "CD",
                "continent_code" => "AF",
                "name" => "Congo",
                "iso3" => "COD",
                "number" => "180",
                "full_name" => "Democratic Republic of the Congo",
                "flag" => "CD.png",
                "continent_id" => 1,
            ],
            [
                "id" => 53,
                "code" => "CG",
                "continent_code" => "AF",
                "name" => "Congo",
                "iso3" => "COG",
                "number" => "178",
                "full_name" => "Republic of the Congo",
                "flag" => "CG.png",
                "continent_id" => 1,
            ],
            [
                "id" => 54,
                "code" => "CK",
                "continent_code" => "OC",
                "name" => "Cook Islands",
                "iso3" => "COK",
                "number" => "184",
                "full_name" => "Cook Islands",
                "flag" => "CK.png",
                "continent_id" => 6,
            ],
            [
                "id" => 55,
                "code" => "CR",
                "continent_code" => "NA",
                "name" => "Costa Rica",
                "iso3" => "CRI",
                "number" => "188",
                "full_name" => "Republic of Costa Rica",
                "flag" => "CR.png",
                "continent_id" => 4,
            ],
            [
                "id" => 56,
                "code" => "CI",
                "continent_code" => "AF",
                "name" => "Cote d\\\'Ivoire",
                "iso3" => "CIV",
                "number" => "384",
                "full_name" => "Republic of Cote d\\\'Ivoire",
                "flag" => "CI.png",
                "continent_id" => 1,
            ],
            [
                "id" => 57,
                "code" => "HR",
                "continent_code" => "EU",
                "name" => "Croatia",
                "iso3" => "HRV",
                "number" => "191",
                "full_name" => "Republic of Croatia",
                "flag" => "HR.png",
                "continent_id" => 3,
            ],
            [
                "id" => 58,
                "code" => "CU",
                "continent_code" => "NA",
                "name" => "Cuba",
                "iso3" => "CUB",
                "number" => "192",
                "full_name" => "Republic of Cuba",
                "flag" => "CU.png",
                "continent_id" => 4,
            ],
            [
                "id" => 59,
                "code" => "CW",
                "continent_code" => "NA",
                "name" => "Curaçao",
                "iso3" => "CUW",
                "number" => "531",
                "full_name" => "Curaçao",
                "flag" => "CW.png",
                "continent_id" => 4,
            ],
            [
                "id" => 60,
                "code" => "CY",
                "continent_code" => "AS",
                "name" => "Cyprus",
                "iso3" => "CYP",
                "number" => "196",
                "full_name" => "Republic of Cyprus",
                "flag" => "CY.png",
                "continent_id" => 2,
            ],
            [
                "id" => 61,
                "code" => "CZ",
                "continent_code" => "EU",
                "name" => "Czechia",
                "iso3" => "CZE",
                "number" => "203",
                "full_name" => "Czech Republic",
                "flag" => "CZ.png",
                "continent_id" => 3,
            ],
            [
                "id" => 62,
                "code" => "DK",
                "continent_code" => "EU",
                "name" => "Denmark",
                "iso3" => "DNK",
                "number" => "208",
                "full_name" => "Kingdom of Denmark",
                "flag" => "DK.png",
                "continent_id" => 3,
            ],
            [
                "id" => 63,
                "code" => "DJ",
                "continent_code" => "AF",
                "name" => "Djibouti",
                "iso3" => "DJI",
                "number" => "262",
                "full_name" => "Republic of Djibouti",
                "flag" => "DJ.png",
                "continent_id" => 1,
            ],
            [
                "id" => 64,
                "code" => "DM",
                "continent_code" => "NA",
                "name" => "Dominica",
                "iso3" => "DMA",
                "number" => "212",
                "full_name" => "Commonwealth of Dominica",
                "flag" => "DM.png",
                "continent_id" => 4,
            ],
            [
                "id" => 65,
                "code" => "DO",
                "continent_code" => "NA",
                "name" => "Dominican Republic",
                "iso3" => "DOM",
                "number" => "214",
                "full_name" => "Dominican Republic",
                "flag" => "DO.png",
                "continent_id" => 4,
            ],
            [
                "id" => 66,
                "code" => "EC",
                "continent_code" => "SA",
                "name" => "Ecuador",
                "iso3" => "ECU",
                "number" => "218",
                "full_name" => "Republic of Ecuador",
                "flag" => "EC.png",
                "continent_id" => 5,
            ],
            [
                "id" => 67,
                "code" => "EG",
                "continent_code" => "AF",
                "name" => "Egypt",
                "iso3" => "EGY",
                "number" => "818",
                "full_name" => "Arab Republic of Egypt",
                "flag" => "EG.png",
                "continent_id" => 1,
            ],
            [
                "id" => 68,
                "code" => "SV",
                "continent_code" => "NA",
                "name" => "El Salvador",
                "iso3" => "SLV",
                "number" => "222",
                "full_name" => "Republic of El Salvador",
                "flag" => "SV.png",
                "continent_id" => 4,
            ],
            [
                "id" => 69,
                "code" => "GQ",
                "continent_code" => "AF",
                "name" => "Equatorial Guinea",
                "iso3" => "GNQ",
                "number" => "226",
                "full_name" => "Republic of Equatorial Guinea",
                "flag" => "GQ.png",
                "continent_id" => 1,
            ],
            [
                "id" => 70,
                "code" => "ER",
                "continent_code" => "AF",
                "name" => "Eritrea",
                "iso3" => "ERI",
                "number" => "232",
                "full_name" => "State of Eritrea",
                "flag" => "ER.png",
                "continent_id" => 1,
            ],
            [
                "id" => 71,
                "code" => "EE",
                "continent_code" => "EU",
                "name" => "Estonia",
                "iso3" => "EST",
                "number" => "233",
                "full_name" => "Republic of Estonia",
                "flag" => "EE.png",
                "continent_id" => 3,
            ],
            [
                "id" => 72,
                "code" => "ET",
                "continent_code" => "AF",
                "name" => "Ethiopia",
                "iso3" => "ETH",
                "number" => "231",
                "full_name" => "Federal Democratic Republic of Ethiopia",
                "flag" => "ET.png",
                "continent_id" => 1,
            ],
            [
                "id" => 73,
                "code" => "FO",
                "continent_code" => "EU",
                "name" => "Faroe Islands",
                "iso3" => "FRO",
                "number" => "234",
                "full_name" => "Faroe Islands",
                "flag" => "FO.png",
                "continent_id" => 3,
            ],
            [
                "id" => 74,
                "code" => "FK",
                "continent_code" => "SA",
                "name" => "Falkland Islands (Malvinas)",
                "iso3" => "FLK",
                "number" => "238",
                "full_name" => "Falkland Islands (Malvinas)",
                "flag" => "FK.png",
                "continent_id" => 5,
            ],
            [
                "id" => 75,
                "code" => "FJ",
                "continent_code" => "OC",
                "name" => "Fiji",
                "iso3" => "FJI",
                "number" => "242",
                "full_name" => "Republic of Fiji",
                "flag" => "FJ.png",
                "continent_id" => 6,
            ],
            [
                "id" => 76,
                "code" => "FI",
                "continent_code" => "EU",
                "name" => "Finland",
                "iso3" => "FIN",
                "number" => "246",
                "full_name" => "Republic of Finland",
                "flag" => "FI.png",
                "continent_id" => 3,
            ],
            [
                "id" => 77,
                "code" => "FR",
                "continent_code" => "EU",
                "name" => "France",
                "iso3" => "FRA",
                "number" => "250",
                "full_name" => "French Republic",
                "flag" => "FR.png",
                "continent_id" => 3,
            ],
            [
                "id" => 78,
                "code" => "GF",
                "continent_code" => "SA",
                "name" => "French Guiana",
                "iso3" => "GUF",
                "number" => "254",
                "full_name" => "French Guiana",
                "flag" => "GF.png",
                "continent_id" => 5,
            ],
            [
                "id" => 79,
                "code" => "PF",
                "continent_code" => "OC",
                "name" => "French Polynesia",
                "iso3" => "PYF",
                "number" => "258",
                "full_name" => "French Polynesia",
                "flag" => "PF.png",
                "continent_id" => 6,
            ],
            [
                "id" => 80,
                "code" => "TF",
                "continent_code" => "AN",
                "name" => "French Southern Territories",
                "iso3" => "ATF",
                "number" => "260",
                "full_name" => "French Southern Territories",
                "flag" => "TF.png",
                "continent_id" => 7,
            ],
            [
                "id" => 81,
                "code" => "GA",
                "continent_code" => "AF",
                "name" => "Gabon",
                "iso3" => "GAB",
                "number" => "266",
                "full_name" => "Gabonese Republic",
                "flag" => "GA.png",
                "continent_id" => 1,
            ],
            [
                "id" => 82,
                "code" => "GM",
                "continent_code" => "AF",
                "name" => "Gambia",
                "iso3" => "GMB",
                "number" => "270",
                "full_name" => "Republic of the Gambia",
                "flag" => "GM.png",
                "continent_id" => 1,
            ],
            [
                "id" => 83,
                "code" => "GE",
                "continent_code" => "AS",
                "name" => "Georgia",
                "iso3" => "GEO",
                "number" => "268",
                "full_name" => "Georgia",
                "flag" => "GE.png",
                "continent_id" => 2,
            ],
            [
                "id" => 84,
                "code" => "DE",
                "continent_code" => "EU",
                "name" => "Germany",
                "iso3" => "DEU",
                "number" => "276",
                "full_name" => "Federal Republic of Germany",
                "flag" => "DE.png",
                "continent_id" => 3,
            ],
            [
                "id" => 85,
                "code" => "GH",
                "continent_code" => "AF",
                "name" => "Ghana",
                "iso3" => "GHA",
                "number" => "288",
                "full_name" => "Republic of Ghana",
                "flag" => "GH.png",
                "continent_id" => 1,
            ],
            [
                "id" => 86,
                "code" => "GI",
                "continent_code" => "EU",
                "name" => "Gibraltar",
                "iso3" => "GIB",
                "number" => "292",
                "full_name" => "Gibraltar",
                "flag" => "GI.png",
                "continent_id" => 3,
            ],
            [
                "id" => 87,
                "code" => "GR",
                "continent_code" => "EU",
                "name" => "Greece",
                "iso3" => "GRC",
                "number" => "300",
                "full_name" => "Hellenic Republic of Greece",
                "flag" => "GR.png",
                "continent_id" => 3,
            ],
            [
                "id" => 88,
                "code" => "GL",
                "continent_code" => "NA",
                "name" => "Greenland",
                "iso3" => "GRL",
                "number" => "304",
                "full_name" => "Greenland",
                "flag" => "GL.png",
                "continent_id" => 4,
            ],
            [
                "id" => 89,
                "code" => "GD",
                "continent_code" => "NA",
                "name" => "Grenada",
                "iso3" => "GRD",
                "number" => "308",
                "full_name" => "Grenada",
                "flag" => "GD.png",
                "continent_id" => 4,
            ],
            [
                "id" => 90,
                "code" => "GP",
                "continent_code" => "NA",
                "name" => "Guadeloupe",
                "iso3" => "GLP",
                "number" => "312",
                "full_name" => "Guadeloupe",
                "flag" => "GP.png",
                "continent_id" => 4,
            ],
            [
                "id" => 91,
                "code" => "GU",
                "continent_code" => "OC",
                "name" => "Guam",
                "iso3" => "GUM",
                "number" => "316",
                "full_name" => "Guam",
                "flag" => "GU.png",
                "continent_id" => 6,
            ],
            [
                "id" => 92,
                "code" => "GT",
                "continent_code" => "NA",
                "name" => "Guatemala",
                "iso3" => "GTM",
                "number" => "320",
                "full_name" => "Republic of Guatemala",
                "flag" => "GT.png",
                "continent_id" => 4,
            ],
            [
                "id" => 93,
                "code" => "GG",
                "continent_code" => "EU",
                "name" => "Guernsey",
                "iso3" => "GGY",
                "number" => "831",
                "full_name" => "Bailiwick of Guernsey",
                "flag" => "GG.png",
                "continent_id" => 3,
            ],
            [
                "id" => 94,
                "code" => "GN",
                "continent_code" => "AF",
                "name" => "Guinea",
                "iso3" => "GIN",
                "number" => "324",
                "full_name" => "Republic of Guinea",
                "flag" => "GN.png",
                "continent_id" => 1,
            ],
            [
                "id" => 95,
                "code" => "GW",
                "continent_code" => "AF",
                "name" => "Guinea-Bissau",
                "iso3" => "GNB",
                "number" => "624",
                "full_name" => "Republic of Guinea-Bissau",
                "flag" => "GW.png",
                "continent_id" => 1,
            ],
            [
                "id" => 96,
                "code" => "GY",
                "continent_code" => "SA",
                "name" => "Guyana",
                "iso3" => "GUY",
                "number" => "328",
                "full_name" => "Co-operative Republic of Guyana",
                "flag" => "GY.png",
                "continent_id" => 5,
            ],
            [
                "id" => 97,
                "code" => "HT",
                "continent_code" => "NA",
                "name" => "Haiti",
                "iso3" => "HTI",
                "number" => "332",
                "full_name" => "Republic of Haiti",
                "flag" => "HT.png",
                "continent_id" => 4,
            ],
            [
                "id" => 98,
                "code" => "HM",
                "continent_code" => "AN",
                "name" => "Heard Island and McDonald Islands",
                "iso3" => "HMD",
                "number" => "334",
                "full_name" => "Heard Island and McDonald Islands",
                "flag" => "HM.png",
                "continent_id" => 7,
            ],
            [
                "id" => 99,
                "code" => "VA",
                "continent_code" => "EU",
                "name" => "Holy See (Vatican City State)",
                "iso3" => "VAT",
                "number" => "336",
                "full_name" => "Holy See (Vatican City State)",
                "flag" => "VA.png",
                "continent_id" => 3,
            ],
            [
                "id" => 100,
                "code" => "HN",
                "continent_code" => "NA",
                "name" => "Honduras",
                "iso3" => "HND",
                "number" => "340",
                "full_name" => "Republic of Honduras",
                "flag" => "HN.png",
                "continent_id" => 4,
            ],
            [
                "id" => 101,
                "code" => "HK",
                "continent_code" => "AS",
                "name" => "Hong Kong",
                "iso3" => "HKG",
                "number" => "344",
                "full_name" => "Hong Kong Special Administrative Region of China",
                "flag" => "HK.png",
                "continent_id" => 2,
            ],
            [
                "id" => 102,
                "code" => "HU",
                "continent_code" => "EU",
                "name" => "Hungary",
                "iso3" => "HUN",
                "number" => "348",
                "full_name" => "Hungary",
                "flag" => "HU.png",
                "continent_id" => 3,
            ],
            [
                "id" => 103,
                "code" => "IS",
                "continent_code" => "EU",
                "name" => "Iceland",
                "iso3" => "ISL",
                "number" => "352",
                "full_name" => "Iceland",
                "flag" => "IS.png",
                "continent_id" => 3,
            ],
            [
                "id" => 104,
                "code" => "IN",
                "continent_code" => "AS",
                "name" => "India",
                "iso3" => "IND",
                "number" => "356",
                "full_name" => "Republic of India",
                "flag" => "IN.png",
                "continent_id" => 2,
            ],
            [
                "id" => 105,
                "code" => "ID",
                "continent_code" => "AS",
                "name" => "Indonesia",
                "iso3" => "IDN",
                "number" => "360",
                "full_name" => "Republic of Indonesia",
                "flag" => "ID.png",
                "continent_id" => 2,
            ],
            [
                "id" => 106,
                "code" => "IR",
                "continent_code" => "AS",
                "name" => "Iran",
                "iso3" => "IRN",
                "number" => "364",
                "full_name" => "Islamic Republic of Iran",
                "flag" => "IR.png",
                "continent_id" => 2,
            ],
            [
                "id" => 107,
                "code" => "IQ",
                "continent_code" => "AS",
                "name" => "Iraq",
                "iso3" => "IRQ",
                "number" => "368",
                "full_name" => "Republic of Iraq",
                "flag" => "IQ.png",
                "continent_id" => 2,
            ],
            [
                "id" => 108,
                "code" => "IE",
                "continent_code" => "EU",
                "name" => "Ireland",
                "iso3" => "IRL",
                "number" => "372",
                "full_name" => "Ireland",
                "flag" => "IE.png",
                "continent_id" => 3,
            ],
            [
                "id" => 109,
                "code" => "IM",
                "continent_code" => "EU",
                "name" => "Isle of Man",
                "iso3" => "IMN",
                "number" => "833",
                "full_name" => "Isle of Man",
                "flag" => "IM.png",
                "continent_id" => 3,
            ],
            [
                "id" => 110,
                "code" => "IL",
                "continent_code" => "AS",
                "name" => "Israel",
                "iso3" => "ISR",
                "number" => "376",
                "full_name" => "State of Israel",
                "flag" => "IL.png",
                "continent_id" => 2,
            ],
            [
                "id" => 111,
                "code" => "IT",
                "continent_code" => "EU",
                "name" => "Italy",
                "iso3" => "ITA",
                "number" => "380",
                "full_name" => "Republic of Italy",
                "flag" => "IT.png",
                "continent_id" => 3,
            ],
            [
                "id" => 112,
                "code" => "JM",
                "continent_code" => "NA",
                "name" => "Jamaica",
                "iso3" => "JAM",
                "number" => "388",
                "full_name" => "Jamaica",
                "flag" => "JM.png",
                "continent_id" => 4,
            ],
            [
                "id" => 113,
                "code" => "JP",
                "continent_code" => "AS",
                "name" => "Japan",
                "iso3" => "JPN",
                "number" => "392",
                "full_name" => "Japan",
                "flag" => "JP.png",
                "continent_id" => 2,
            ],
            [
                "id" => 114,
                "code" => "JE",
                "continent_code" => "EU",
                "name" => "Jersey",
                "iso3" => "JEY",
                "number" => "832",
                "full_name" => "Bailiwick of Jersey",
                "flag" => "JE.png",
                "continent_id" => 3,
            ],
            [
                "id" => 115,
                "code" => "JO",
                "continent_code" => "AS",
                "name" => "Jordan",
                "iso3" => "JOR",
                "number" => "400",
                "full_name" => "Hashemite Kingdom of Jordan",
                "flag" => "JO.png",
                "continent_id" => 2,
            ],
            [
                "id" => 116,
                "code" => "KZ",
                "continent_code" => "AS",
                "name" => "Kazakhstan",
                "iso3" => "KAZ",
                "number" => "398",
                "full_name" => "Republic of Kazakhstan",
                "flag" => "KZ.png",
                "continent_id" => 2,
            ],
            [
                "id" => 117,
                "code" => "KE",
                "continent_code" => "AF",
                "name" => "Kenya",
                "iso3" => "KEN",
                "number" => "404",
                "full_name" => "Republic of Kenya",
                "flag" => "KE.png",
                "continent_id" => 1,
            ],
            [
                "id" => 118,
                "code" => "KI",
                "continent_code" => "OC",
                "name" => "Kiribati",
                "iso3" => "KIR",
                "number" => "296",
                "full_name" => "Republic of Kiribati",
                "flag" => "KI.png",
                "continent_id" => 6,
            ],
            [
                "id" => 119,
                "code" => "KP",
                "continent_code" => "AS",
                "name" => "Korea",
                "iso3" => "PRK",
                "number" => "408",
                "full_name" => "Democratic People\\\'s Republic of Korea",
                "flag" => "KP.png",
                "continent_id" => 2,
            ],
            [
                "id" => 120,
                "code" => "KR",
                "continent_code" => "AS",
                "name" => "Korea",
                "iso3" => "KOR",
                "number" => "410",
                "full_name" => "Republic of Korea",
                "flag" => "KR.png",
                "continent_id" => 2,
            ],
            [
                "id" => 121,
                "code" => "KW",
                "continent_code" => "AS",
                "name" => "Kuwait",
                "iso3" => "KWT",
                "number" => "414",
                "full_name" => "State of Kuwait",
                "flag" => "KW.png",
                "continent_id" => 2,
            ],
            [
                "id" => 122,
                "code" => "KG",
                "continent_code" => "AS",
                "name" => "Kyrgyz Republic",
                "iso3" => "KGZ",
                "number" => "417",
                "full_name" => "Kyrgyz Republic",
                "flag" => "KG.png",
                "continent_id" => 2,
            ],
            [
                "id" => 123,
                "code" => "LA",
                "continent_code" => "AS",
                "name" => "Lao People\\\'s Democratic Republic",
                "iso3" => "LAO",
                "number" => "418",
                "full_name" => "Lao People\\\'s Democratic Republic",
                "flag" => "LA.png",
                "continent_id" => 2,
            ],
            [
                "id" => 124,
                "code" => "LV",
                "continent_code" => "EU",
                "name" => "Latvia",
                "iso3" => "LVA",
                "number" => "428",
                "full_name" => "Republic of Latvia",
                "flag" => "LV.png",
                "continent_id" => 3,
            ],
            [
                "id" => 125,
                "code" => "LB",
                "continent_code" => "AS",
                "name" => "Lebanon",
                "iso3" => "LBN",
                "number" => "422",
                "full_name" => "Lebanese Republic",
                "flag" => "LB.png",
                "continent_id" => 2,
            ],
            [
                "id" => 126,
                "code" => "LS",
                "continent_code" => "AF",
                "name" => "Lesotho",
                "iso3" => "LSO",
                "number" => "426",
                "full_name" => "Kingdom of Lesotho",
                "flag" => "LS.png",
                "continent_id" => 1,
            ],
            [
                "id" => 127,
                "code" => "LR",
                "continent_code" => "AF",
                "name" => "Liberia",
                "iso3" => "LBR",
                "number" => "430",
                "full_name" => "Republic of Liberia",
                "flag" => "LR.png",
                "continent_id" => 1,
            ],
            [
                "id" => 128,
                "code" => "LY",
                "continent_code" => "AF",
                "name" => "Libya",
                "iso3" => "LBY",
                "number" => "434",
                "full_name" => "State of Libya",
                "flag" => "LY.png",
                "continent_id" => 1,
            ],
            [
                "id" => 129,
                "code" => "LI",
                "continent_code" => "EU",
                "name" => "Liechtenstein",
                "iso3" => "LIE",
                "number" => "438",
                "full_name" => "Principality of Liechtenstein",
                "flag" => "LI.png",
                "continent_id" => 3,
            ],
            [
                "id" => 130,
                "code" => "LT",
                "continent_code" => "EU",
                "name" => "Lithuania",
                "iso3" => "LTU",
                "number" => "440",
                "full_name" => "Republic of Lithuania",
                "flag" => "LT.png",
                "continent_id" => 3,
            ],
            [
                "id" => 131,
                "code" => "LU",
                "continent_code" => "EU",
                "name" => "Luxembourg",
                "iso3" => "LUX",
                "number" => "442",
                "full_name" => "Grand Duchy of Luxembourg",
                "flag" => "LU.png",
                "continent_id" => 3,
            ],
            [
                "id" => 132,
                "code" => "MO",
                "continent_code" => "AS",
                "name" => "Macao",
                "iso3" => "MAC",
                "number" => "446",
                "full_name" => "Macao Special Administrative Region of China",
                "flag" => "MO.png",
                "continent_id" => 2,
            ],
            [
                "id" => 133,
                "code" => "MG",
                "continent_code" => "AF",
                "name" => "Madagascar",
                "iso3" => "MDG",
                "number" => "450",
                "full_name" => "Republic of Madagascar",
                "flag" => "MG.png",
                "continent_id" => 1,
            ],
            [
                "id" => 134,
                "code" => "MW",
                "continent_code" => "AF",
                "name" => "Malawi",
                "iso3" => "MWI",
                "number" => "454",
                "full_name" => "Republic of Malawi",
                "flag" => "MW.png",
                "continent_id" => 1,
            ],
            [
                "id" => 135,
                "code" => "MY",
                "continent_code" => "AS",
                "name" => "Malaysia",
                "iso3" => "MYS",
                "number" => "458",
                "full_name" => "Malaysia",
                "flag" => "MY.png",
                "continent_id" => 2,
            ],
            [
                "id" => 136,
                "code" => "MV",
                "continent_code" => "AS",
                "name" => "Maldives",
                "iso3" => "MDV",
                "number" => "462",
                "full_name" => "Republic of Maldives",
                "flag" => "MV.png",
                "continent_id" => 2,
            ],
            [
                "id" => 137,
                "code" => "ML",
                "continent_code" => "AF",
                "name" => "Mali",
                "iso3" => "MLI",
                "number" => "466",
                "full_name" => "Republic of Mali",
                "flag" => "ML.png",
                "continent_id" => 1,
            ],
            [
                "id" => 138,
                "code" => "MT",
                "continent_code" => "EU",
                "name" => "Malta",
                "iso3" => "MLT",
                "number" => "470",
                "full_name" => "Republic of Malta",
                "flag" => "MT.png",
                "continent_id" => 3,
            ],
            [
                "id" => 139,
                "code" => "MH",
                "continent_code" => "OC",
                "name" => "Marshall Islands",
                "iso3" => "MHL",
                "number" => "584",
                "full_name" => "Republic of the Marshall Islands",
                "flag" => "MH.png",
                "continent_id" => 6,
            ],
            [
                "id" => 140,
                "code" => "MQ",
                "continent_code" => "NA",
                "name" => "Martinique",
                "iso3" => "MTQ",
                "number" => "474",
                "full_name" => "Martinique",
                "flag" => "MQ.png",
                "continent_id" => 4,
            ],
            [
                "id" => 141,
                "code" => "MR",
                "continent_code" => "AF",
                "name" => "Mauritania",
                "iso3" => "MRT",
                "number" => "478",
                "full_name" => "Islamic Republic of Mauritania",
                "flag" => "MR.png",
                "continent_id" => 1,
            ],
            [
                "id" => 142,
                "code" => "MU",
                "continent_code" => "AF",
                "name" => "Mauritius",
                "iso3" => "MUS",
                "number" => "480",
                "full_name" => "Republic of Mauritius",
                "flag" => "MU.png",
                "continent_id" => 1,
            ],
            [
                "id" => 143,
                "code" => "YT",
                "continent_code" => "AF",
                "name" => "Mayotte",
                "iso3" => "MYT",
                "number" => "175",
                "full_name" => "Mayotte",
                "flag" => "YT.png",
                "continent_id" => 1,
            ],
            [
                "id" => 144,
                "code" => "MX",
                "continent_code" => "NA",
                "name" => "Mexico",
                "iso3" => "MEX",
                "number" => "484",
                "full_name" => "United Mexican States",
                "flag" => "MX.png",
                "continent_id" => 4,
            ],
            [
                "id" => 145,
                "code" => "FM",
                "continent_code" => "OC",
                "name" => "Micronesia",
                "iso3" => "FSM",
                "number" => "583",
                "full_name" => "Federated States of Micronesia",
                "flag" => "FM.png",
                "continent_id" => 6,
            ],
            [
                "id" => 146,
                "code" => "MD",
                "continent_code" => "EU",
                "name" => "Moldova",
                "iso3" => "MDA",
                "number" => "498",
                "full_name" => "Republic of Moldova",
                "flag" => "MD.png",
                "continent_id" => 3,
            ],
            [
                "id" => 147,
                "code" => "MC",
                "continent_code" => "EU",
                "name" => "Monaco",
                "iso3" => "MCO",
                "number" => "492",
                "full_name" => "Principality of Monaco",
                "flag" => "MC.png",
                "continent_id" => 3,
            ],
            [
                "id" => 148,
                "code" => "MN",
                "continent_code" => "AS",
                "name" => "Mongolia",
                "iso3" => "MNG",
                "number" => "496",
                "full_name" => "Mongolia",
                "flag" => "MN.png",
                "continent_id" => 2,
            ],
            [
                "id" => 149,
                "code" => "ME",
                "continent_code" => "EU",
                "name" => "Montenegro",
                "iso3" => "MNE",
                "number" => "499",
                "full_name" => "Montenegro",
                "flag" => "ME.png",
                "continent_id" => 3,
            ],
            [
                "id" => 150,
                "code" => "MS",
                "continent_code" => "NA",
                "name" => "Montserrat",
                "iso3" => "MSR",
                "number" => "500",
                "full_name" => "Montserrat",
                "flag" => "MS.png",
                "continent_id" => 4,
            ],
            [
                "id" => 151,
                "code" => "MA",
                "continent_code" => "AF",
                "name" => "Morocco",
                "iso3" => "MAR",
                "number" => "504",
                "full_name" => "Kingdom of Morocco",
                "flag" => "MA.png",
                "continent_id" => 1,
            ],
            [
                "id" => 152,
                "code" => "MZ",
                "continent_code" => "AF",
                "name" => "Mozambique",
                "iso3" => "MOZ",
                "number" => "508",
                "full_name" => "Republic of Mozambique",
                "flag" => "MZ.png",
                "continent_id" => 1,
            ],
            [
                "id" => 153,
                "code" => "MM",
                "continent_code" => "AS",
                "name" => "Myanmar",
                "iso3" => "MMR",
                "number" => "104",
                "full_name" => "Republic of the Union of Myanmar",
                "flag" => "MM.png",
                "continent_id" => 2,
            ],
            [
                "id" => 154,
                "code" => "NA",
                "continent_code" => "AF",
                "name" => "Namibia",
                "iso3" => "NAM",
                "number" => "516",
                "full_name" => "Republic of Namibia",
                "flag" => "NA.png",
                "continent_id" => 1,
            ],
            [
                "id" => 155,
                "code" => "NR",
                "continent_code" => "OC",
                "name" => "Nauru",
                "iso3" => "NRU",
                "number" => "520",
                "full_name" => "Republic of Nauru",
                "flag" => "NR.png",
                "continent_id" => 6,
            ],
            [
                "id" => 156,
                "code" => "NP",
                "continent_code" => "AS",
                "name" => "Nepal",
                "iso3" => "NPL",
                "number" => "524",
                "full_name" => "Nepal",
                "flag" => "NP.png",
                "continent_id" => 2,
            ],
            [
                "id" => 157,
                "code" => "NL",
                "continent_code" => "EU",
                "name" => "Netherlands",
                "iso3" => "NLD",
                "number" => "528",
                "full_name" => "Kingdom of the Netherlands",
                "flag" => "NL.png",
                "continent_id" => 3,
            ],
            [
                "id" => 158,
                "code" => "NC",
                "continent_code" => "OC",
                "name" => "New Caledonia",
                "iso3" => "NCL",
                "number" => "540",
                "full_name" => "New Caledonia",
                "flag" => "NC.png",
                "continent_id" => 6,
            ],
            [
                "id" => 159,
                "code" => "NZ",
                "continent_code" => "OC",
                "name" => "New Zealand",
                "iso3" => "NZL",
                "number" => "554",
                "full_name" => "New Zealand",
                "flag" => "NZ.png",
                "continent_id" => 6,
            ],
            [
                "id" => 160,
                "code" => "NI",
                "continent_code" => "NA",
                "name" => "Nicaragua",
                "iso3" => "NIC",
                "number" => "558",
                "full_name" => "Republic of Nicaragua",
                "flag" => "NI.png",
                "continent_id" => 4,
            ],
            [
                "id" => 161,
                "code" => "NE",
                "continent_code" => "AF",
                "name" => "Niger",
                "iso3" => "NER",
                "number" => "562",
                "full_name" => "Republic of Niger",
                "flag" => "NE.png",
                "continent_id" => 1,
            ],
            [
                "id" => 162,
                "code" => "NG",
                "continent_code" => "AF",
                "name" => "Nigeria",
                "iso3" => "NGA",
                "number" => "566",
                "full_name" => "Federal Republic of Nigeria",
                "flag" => "NG.png",
                "continent_id" => 1,
            ],
            [
                "id" => 163,
                "code" => "NU",
                "continent_code" => "OC",
                "name" => "Niue",
                "iso3" => "NIU",
                "number" => "570",
                "full_name" => "Niue",
                "flag" => "NU.png",
                "continent_id" => 6,
            ],
            [
                "id" => 164,
                "code" => "NF",
                "continent_code" => "OC",
                "name" => "Norfolk Island",
                "iso3" => "NFK",
                "number" => "574",
                "full_name" => "Norfolk Island",
                "flag" => "NF.png",
                "continent_id" => 6,
            ],
            [
                "id" => 165,
                "code" => "MK",
                "continent_code" => "EU",
                "name" => "North Macedonia",
                "iso3" => "MKD",
                "number" => "807",
                "full_name" => "Republic of North Macedonia",
                "flag" => "MK.png",
                "continent_id" => 3,
            ],
            [
                "id" => 166,
                "code" => "MP",
                "continent_code" => "OC",
                "name" => "Northern Mariana Islands",
                "iso3" => "MNP",
                "number" => "580",
                "full_name" => "Commonwealth of the Northern Mariana Islands",
                "flag" => "MP.png",
                "continent_id" => 6,
            ],
            [
                "id" => 167,
                "code" => "NO",
                "continent_code" => "EU",
                "name" => "Norway",
                "iso3" => "NOR",
                "number" => "578",
                "full_name" => "Kingdom of Norway",
                "flag" => "NO.png",
                "continent_id" => 3,
            ],
            [
                "id" => 168,
                "code" => "OM",
                "continent_code" => "AS",
                "name" => "Oman",
                "iso3" => "OMN",
                "number" => "512",
                "full_name" => "Sultanate of Oman",
                "flag" => "OM.png",
                "continent_id" => 2,
            ],
            [
                "id" => 169,
                "code" => "PK",
                "continent_code" => "AS",
                "name" => "Pakistan",
                "iso3" => "PAK",
                "number" => "586",
                "full_name" => "Islamic Republic of Pakistan",
                "flag" => "PK.png",
                "continent_id" => 2,
            ],
            [
                "id" => 170,
                "code" => "PW",
                "continent_code" => "OC",
                "name" => "Palau",
                "iso3" => "PLW",
                "number" => "585",
                "full_name" => "Republic of Palau",
                "flag" => "PW.png",
                "continent_id" => 6,
            ],
            [
                "id" => 171,
                "code" => "PS",
                "continent_code" => "AS",
                "name" => "Palestine",
                "iso3" => "PSE",
                "number" => "275",
                "full_name" => "State of Palestine",
                "flag" => "PS.png",
                "continent_id" => 2,
            ],
            [
                "id" => 172,
                "code" => "PA",
                "continent_code" => "NA",
                "name" => "Panama",
                "iso3" => "PAN",
                "number" => "591",
                "full_name" => "Republic of Panama",
                "flag" => "PA.png",
                "continent_id" => 4,
            ],
            [
                "id" => 173,
                "code" => "PG",
                "continent_code" => "OC",
                "name" => "Papua New Guinea",
                "iso3" => "PNG",
                "number" => "598",
                "full_name" => "Independent State of Papua New Guinea",
                "flag" => "PG.png",
                "continent_id" => 6,
            ],
            [
                "id" => 174,
                "code" => "PY",
                "continent_code" => "SA",
                "name" => "Paraguay",
                "iso3" => "PRY",
                "number" => "600",
                "full_name" => "Republic of Paraguay",
                "flag" => "PY.png",
                "continent_id" => 5,
            ],
            [
                "id" => 175,
                "code" => "PE",
                "continent_code" => "SA",
                "name" => "Peru",
                "iso3" => "PER",
                "number" => "604",
                "full_name" => "Republic of Peru",
                "flag" => "PE.png",
                "continent_id" => 5,
            ],
            [
                "id" => 176,
                "code" => "PH",
                "continent_code" => "AS",
                "name" => "Philippines",
                "iso3" => "PHL",
                "number" => "608",
                "full_name" => "Republic of the Philippines",
                "flag" => "PH.png",
                "continent_id" => 2,
            ],
            [
                "id" => 177,
                "code" => "PN",
                "continent_code" => "OC",
                "name" => "Pitcairn Islands",
                "iso3" => "PCN",
                "number" => "612",
                "full_name" => "Pitcairn Islands",
                "flag" => "PN.png",
                "continent_id" => 6,
            ],
            [
                "id" => 178,
                "code" => "PL",
                "continent_code" => "EU",
                "name" => "Poland",
                "iso3" => "POL",
                "number" => "616",
                "full_name" => "Republic of Poland",
                "flag" => "PL.png",
                "continent_id" => 3,
            ],
            [
                "id" => 179,
                "code" => "PT",
                "continent_code" => "EU",
                "name" => "Portugal",
                "iso3" => "PRT",
                "number" => "620",
                "full_name" => "Portuguese Republic",
                "flag" => "PT.png",
                "continent_id" => 3,
            ],
            [
                "id" => 180,
                "code" => "PR",
                "continent_code" => "NA",
                "name" => "Puerto Rico",
                "iso3" => "PRI",
                "number" => "630",
                "full_name" => "Commonwealth of Puerto Rico",
                "flag" => "PR.png",
                "continent_id" => 4,
            ],
            [
                "id" => 181,
                "code" => "QA",
                "continent_code" => "AS",
                "name" => "Qatar",
                "iso3" => "QAT",
                "number" => "634",
                "full_name" => "State of Qatar",
                "flag" => "QA.png",
                "continent_id" => 2,
            ],
            [
                "id" => 182,
                "code" => "RE",
                "continent_code" => "AF",
                "name" => "Réunion",
                "iso3" => "REU",
                "number" => "638",
                "full_name" => "Réunion",
                "flag" => "RE.png",
                "continent_id" => 1,
            ],
            [
                "id" => 183,
                "code" => "RO",
                "continent_code" => "EU",
                "name" => "Romania",
                "iso3" => "ROU",
                "number" => "642",
                "full_name" => "Romania",
                "flag" => "RO.png",
                "continent_id" => 3,
            ],
            [
                "id" => 184,
                "code" => "RU",
                "continent_code" => "EU",
                "name" => "Russian Federation",
                "iso3" => "RUS",
                "number" => "643",
                "full_name" => "Russian Federation",
                "flag" => "RU.png",
                "continent_id" => 3,
            ],
            [
                "id" => 185,
                "code" => "RW",
                "continent_code" => "AF",
                "name" => "Rwanda",
                "iso3" => "RWA",
                "number" => "646",
                "full_name" => "Republic of Rwanda",
                "flag" => "RW.png",
                "continent_id" => 1,
            ],
            [
                "id" => 186,
                "code" => "BL",
                "continent_code" => "NA",
                "name" => "Saint Barthélemy",
                "iso3" => "BLM",
                "number" => "652",
                "full_name" => "Saint Barthélemy",
                "flag" => "BL.png",
                "continent_id" => 4,
            ],
            [
                "id" => 187,
                "code" => "SH",
                "continent_code" => "AF",
                "name" => "Saint Helena, Ascension and Tristan da Cunha",
                "iso3" => "SHN",
                "number" => "654",
                "full_name" => "Saint Helena, Ascension and Tristan da Cunha",
                "flag" => "SH.png",
                "continent_id" => 1,
            ],
            [
                "id" => 188,
                "code" => "KN",
                "continent_code" => "NA",
                "name" => "Saint Kitts and Nevis",
                "iso3" => "KNA",
                "number" => "659",
                "full_name" => "Federation of Saint Kitts and Nevis",
                "flag" => "KN.png",
                "continent_id" => 4,
            ],
            [
                "id" => 189,
                "code" => "LC",
                "continent_code" => "NA",
                "name" => "Saint Lucia",
                "iso3" => "LCA",
                "number" => "662",
                "full_name" => "Saint Lucia",
                "flag" => "LC.png",
                "continent_id" => 4,
            ],
            [
                "id" => 190,
                "code" => "MF",
                "continent_code" => "NA",
                "name" => "Saint Martin",
                "iso3" => "MAF",
                "number" => "663",
                "full_name" => "Saint Martin (French part)",
                "flag" => "MF.png",
                "continent_id" => 4,
            ],
            [
                "id" => 191,
                "code" => "PM",
                "continent_code" => "NA",
                "name" => "Saint Pierre and Miquelon",
                "iso3" => "SPM",
                "number" => "666",
                "full_name" => "Saint Pierre and Miquelon",
                "flag" => "PM.png",
                "continent_id" => 4,
            ],
            [
                "id" => 192,
                "code" => "VC",
                "continent_code" => "NA",
                "name" => "Saint Vincent and the Grenadines",
                "iso3" => "VCT",
                "number" => "670",
                "full_name" => "Saint Vincent and the Grenadines",
                "flag" => "VC.png",
                "continent_id" => 4,
            ],
            [
                "id" => 193,
                "code" => "WS",
                "continent_code" => "OC",
                "name" => "Samoa",
                "iso3" => "WSM",
                "number" => "882",
                "full_name" => "Independent State of Samoa",
                "flag" => "WS.png",
                "continent_id" => 6,
            ],
            [
                "id" => 194,
                "code" => "SM",
                "continent_code" => "EU",
                "name" => "San Marino",
                "iso3" => "SMR",
                "number" => "674",
                "full_name" => "Republic of San Marino",
                "flag" => "SM.png",
                "continent_id" => 3,
            ],
            [
                "id" => 195,
                "code" => "ST",
                "continent_code" => "AF",
                "name" => "Sao Tome and Principe",
                "iso3" => "STP",
                "number" => "678",
                "full_name" => "Democratic Republic of Sao Tome and Principe",
                "flag" => "ST.png",
                "continent_id" => 1,
            ],
            [
                "id" => 196,
                "code" => "SA",
                "continent_code" => "AS",
                "name" => "Saudi Arabia",
                "iso3" => "SAU",
                "number" => "682",
                "full_name" => "Kingdom of Saudi Arabia",
                "flag" => "SA.png",
                "continent_id" => 2,
            ],
            [
                "id" => 197,
                "code" => "SN",
                "continent_code" => "AF",
                "name" => "Senegal",
                "iso3" => "SEN",
                "number" => "686",
                "full_name" => "Republic of Senegal",
                "flag" => "SN.png",
                "continent_id" => 1,
            ],
            [
                "id" => 198,
                "code" => "RS",
                "continent_code" => "EU",
                "name" => "Serbia",
                "iso3" => "SRB",
                "number" => "688",
                "full_name" => "Republic of Serbia",
                "flag" => "RS.png",
                "continent_id" => 3,
            ],
            [
                "id" => 199,
                "code" => "SC",
                "continent_code" => "AF",
                "name" => "Seychelles",
                "iso3" => "SYC",
                "number" => "690",
                "full_name" => "Republic of Seychelles",
                "flag" => "SC.png",
                "continent_id" => 1,
            ],
            [
                "id" => 200,
                "code" => "SL",
                "continent_code" => "AF",
                "name" => "Sierra Leone",
                "iso3" => "SLE",
                "number" => "694",
                "full_name" => "Republic of Sierra Leone",
                "flag" => "SL.png",
                "continent_id" => 1,
            ],
            [
                "id" => 201,
                "code" => "SG",
                "continent_code" => "AS",
                "name" => "Singapore",
                "iso3" => "SGP",
                "number" => "702",
                "full_name" => "Republic of Singapore",
                "flag" => "SG.png",
                "continent_id" => 2,
            ],
            [
                "id" => 202,
                "code" => "SX",
                "continent_code" => "NA",
                "name" => "Sint Maarten (Dutch part)",
                "iso3" => "SXM",
                "number" => "534",
                "full_name" => "Sint Maarten (Dutch part)",
                "flag" => "SX.png",
                "continent_id" => 4,
            ],
            [
                "id" => 203,
                "code" => "SK",
                "continent_code" => "EU",
                "name" => "Slovakia (Slovak Republic)",
                "iso3" => "SVK",
                "number" => "703",
                "full_name" => "Slovakia (Slovak Republic)",
                "flag" => "SK.png",
                "continent_id" => 3,
            ],
            [
                "id" => 204,
                "code" => "SI",
                "continent_code" => "EU",
                "name" => "Slovenia",
                "iso3" => "SVN",
                "number" => "705",
                "full_name" => "Republic of Slovenia",
                "flag" => "SI.png",
                "continent_id" => 3,
            ],
            [
                "id" => 205,
                "code" => "SB",
                "continent_code" => "OC",
                "name" => "Solomon Islands",
                "iso3" => "SLB",
                "number" => "090",
                "full_name" => "Solomon Islands",
                "flag" => "SB.png",
                "continent_id" => 6,
            ],
            [
                "id" => 206,
                "code" => "SO",
                "continent_code" => "AF",
                "name" => "Somalia",
                "iso3" => "SOM",
                "number" => "706",
                "full_name" => "Federal Republic of Somalia",
                "flag" => "SO.png",
                "continent_id" => 1,
            ],
            [
                "id" => 207,
                "code" => "ZA",
                "continent_code" => "AF",
                "name" => "South Africa",
                "iso3" => "ZAF",
                "number" => "710",
                "full_name" => "Republic of South Africa",
                "flag" => "ZA.png",
                "continent_id" => 1,
            ],
            [
                "id" => 208,
                "code" => "GS",
                "continent_code" => "AN",
                "name" => "South Georgia and the South Sandwich Islands",
                "iso3" => "SGS",
                "number" => "239",
                "full_name" => "South Georgia and the South Sandwich Islands",
                "flag" => "GS.png",
                "continent_id" => 7,
            ],
            [
                "id" => 209,
                "code" => "SS",
                "continent_code" => "AF",
                "name" => "South Sudan",
                "iso3" => "SSD",
                "number" => "728",
                "full_name" => "Republic of South Sudan",
                "flag" => "SS.png",
                "continent_id" => 1,
            ],
            [
                "id" => 210,
                "code" => "ES",
                "continent_code" => "EU",
                "name" => "Spain",
                "iso3" => "ESP",
                "number" => "724",
                "full_name" => "Kingdom of Spain",
                "flag" => "ES.png",
                "continent_id" => 3,
            ],
            [
                "id" => 211,
                "code" => "LK",
                "continent_code" => "AS",
                "name" => "Sri Lanka",
                "iso3" => "LKA",
                "number" => "144",
                "full_name" => "Democratic Socialist Republic of Sri Lanka",
                "flag" => "LK.png",
                "continent_id" => 2,
            ],
            [
                "id" => 212,
                "code" => "SD",
                "continent_code" => "AF",
                "name" => "Sudan",
                "iso3" => "SDN",
                "number" => "729",
                "full_name" => "Republic of Sudan",
                "flag" => "SD.png",
                "continent_id" => 1,
            ],
            [
                "id" => 213,
                "code" => "SR",
                "continent_code" => "SA",
                "name" => "Suriname",
                "iso3" => "SUR",
                "number" => "740",
                "full_name" => "Republic of Suriname",
                "flag" => "SR.png",
                "continent_id" => 5,
            ],
            [
                "id" => 214,
                "code" => "SJ",
                "continent_code" => "EU",
                "name" => "Svalbard & Jan Mayen Islands",
                "iso3" => "SJM",
                "number" => "744",
                "full_name" => "Svalbard & Jan Mayen Islands",
                "flag" => "SJ.png",
                "continent_id" => 3,
            ],
            [
                "id" => 215,
                "code" => "SZ",
                "continent_code" => "AF",
                "name" => "Eswatini",
                "iso3" => "SWZ",
                "number" => "748",
                "full_name" => "Kingdom of Eswatini",
                "flag" => "SZ.png",
                "continent_id" => 1,
            ],
            [
                "id" => 216,
                "code" => "SE",
                "continent_code" => "EU",
                "name" => "Sweden",
                "iso3" => "SWE",
                "number" => "752",
                "full_name" => "Kingdom of Sweden",
                "flag" => "SE.png",
                "continent_id" => 3,
            ],
            [
                "id" => 217,
                "code" => "CH",
                "continent_code" => "EU",
                "name" => "Switzerland",
                "iso3" => "CHE",
                "number" => "756",
                "full_name" => "Swiss Confederation",
                "flag" => "CH.png",
                "continent_id" => 3,
            ],
            [
                "id" => 218,
                "code" => "SY",
                "continent_code" => "AS",
                "name" => "Syrian Arab Republic",
                "iso3" => "SYR",
                "number" => "760",
                "full_name" => "Syrian Arab Republic",
                "flag" => "SY.png",
                "continent_id" => 2,
            ],
            [
                "id" => 219,
                "code" => "TW",
                "continent_code" => "AS",
                "name" => "Taiwan",
                "iso3" => "TWN",
                "number" => "158",
                "full_name" => "Taiwan, Province of China",
                "flag" => "TW.png",
                "continent_id" => 2,
            ],
            [
                "id" => 220,
                "code" => "TJ",
                "continent_code" => "AS",
                "name" => "Tajikistan",
                "iso3" => "TJK",
                "number" => "762",
                "full_name" => "Republic of Tajikistan",
                "flag" => "TJ.png",
                "continent_id" => 2,
            ],
            [
                "id" => 221,
                "code" => "TZ",
                "continent_code" => "AF",
                "name" => "Tanzania",
                "iso3" => "TZA",
                "number" => "834",
                "full_name" => "United Republic of Tanzania",
                "flag" => "TZ.png",
                "continent_id" => 1,
            ],
            [
                "id" => 222,
                "code" => "TH",
                "continent_code" => "AS",
                "name" => "Thailand",
                "iso3" => "THA",
                "number" => "764",
                "full_name" => "Kingdom of Thailand",
                "flag" => "TH.png",
                "continent_id" => 2,
            ],
            [
                "id" => 223,
                "code" => "TL",
                "continent_code" => "AS",
                "name" => "Timor-Leste",
                "iso3" => "TLS",
                "number" => "626",
                "full_name" => "Democratic Republic of Timor-Leste",
                "flag" => "TL.png",
                "continent_id" => 2,
            ],
            [
                "id" => 224,
                "code" => "TG",
                "continent_code" => "AF",
                "name" => "Togo",
                "iso3" => "TGO",
                "number" => "768",
                "full_name" => "Togolese Republic",
                "flag" => "TG.png",
                "continent_id" => 1,
            ],
            [
                "id" => 225,
                "code" => "TK",
                "continent_code" => "OC",
                "name" => "Tokelau",
                "iso3" => "TKL",
                "number" => "772",
                "full_name" => "Tokelau",
                "flag" => "TK.png",
                "continent_id" => 6,
            ],
            [
                "id" => 226,
                "code" => "TO",
                "continent_code" => "OC",
                "name" => "Tonga",
                "iso3" => "TON",
                "number" => "776",
                "full_name" => "Kingdom of Tonga",
                "flag" => "TO.png",
                "continent_id" => 6,
            ],
            [
                "id" => 227,
                "code" => "TT",
                "continent_code" => "NA",
                "name" => "Trinidad and Tobago",
                "iso3" => "TTO",
                "number" => "780",
                "full_name" => "Republic of Trinidad and Tobago",
                "flag" => "TT.png",
                "continent_id" => 4,
            ],
            [
                "id" => 228,
                "code" => "TN",
                "continent_code" => "AF",
                "name" => "Tunisia",
                "iso3" => "TUN",
                "number" => "788",
                "full_name" => "Tunisian Republic",
                "flag" => "TN.png",
                "continent_id" => 1,
            ],
            [
                "id" => 229,
                "code" => "TR",
                "continent_code" => "AS",
                "name" => "Türkiye",
                "iso3" => "TUR",
                "number" => "792",
                "full_name" => "Republic of Türkiye",
                "flag" => "TR.png",
                "continent_id" => 2,
            ],
            [
                "id" => 230,
                "code" => "TM",
                "continent_code" => "AS",
                "name" => "Turkmenistan",
                "iso3" => "TKM",
                "number" => "795",
                "full_name" => "Turkmenistan",
                "flag" => "TM.png",
                "continent_id" => 2,
            ],
            [
                "id" => 231,
                "code" => "TC",
                "continent_code" => "NA",
                "name" => "Turks and Caicos Islands",
                "iso3" => "TCA",
                "number" => "796",
                "full_name" => "Turks and Caicos Islands",
                "flag" => "TC.png",
                "continent_id" => 4,
            ],
            [
                "id" => 232,
                "code" => "TV",
                "continent_code" => "OC",
                "name" => "Tuvalu",
                "iso3" => "TUV",
                "number" => "798",
                "full_name" => "Tuvalu",
                "flag" => "TV.png",
                "continent_id" => 6,
            ],
            [
                "id" => 233,
                "code" => "UG",
                "continent_code" => "AF",
                "name" => "Uganda",
                "iso3" => "UGA",
                "number" => "800",
                "full_name" => "Republic of Uganda",
                "flag" => "UG.png",
                "continent_id" => 1,
            ],
            [
                "id" => 234,
                "code" => "UA",
                "continent_code" => "EU",
                "name" => "Ukraine",
                "iso3" => "UKR",
                "number" => "804",
                "full_name" => "Ukraine",
                "flag" => "UA.png",
                "continent_id" => 3,
            ],
            [
                "id" => 235,
                "code" => "AE",
                "continent_code" => "AS",
                "name" => "United Arab Emirates",
                "iso3" => "ARE",
                "number" => "784",
                "full_name" => "United Arab Emirates",
                "flag" => "AE.png",
                "continent_id" => 2,
            ],
            [
                "id" => 236,
                "code" => "GB",
                "continent_code" => "EU",
                "name" => "United Kingdom of Great Britain and Northern Ireland",
                "iso3" => "GBR",
                "number" => "826",
                "full_name" => "United Kingdom of Great Britain & Northern Ireland",
                "flag" => "GB.png",
                "continent_id" => 3,
            ],
            [
                "id" => 237,
                "code" => "US",
                "continent_code" => "NA",
                "name" => "United States of America",
                "iso3" => "USA",
                "number" => "840",
                "full_name" => "United States of America",
                "flag" => "US.png",
                "continent_id" => 4,
            ],
            [
                "id" => 238,
                "code" => "UM",
                "continent_code" => "OC",
                "name" => "United States Minor Outlying Islands",
                "iso3" => "UMI",
                "number" => "581",
                "full_name" => "United States Minor Outlying Islands",
                "flag" => "UM.png",
                "continent_id" => 6,
            ],
            [
                "id" => 239,
                "code" => "VI",
                "continent_code" => "NA",
                "name" => "United States Virgin Islands",
                "iso3" => "VIR",
                "number" => "850",
                "full_name" => "United States Virgin Islands",
                "flag" => "VI.png",
                "continent_id" => 4,
            ],
            [
                "id" => 240,
                "code" => "UY",
                "continent_code" => "SA",
                "name" => "Uruguay",
                "iso3" => "URY",
                "number" => "858",
                "full_name" => "Eastern Republic of Uruguay",
                "flag" => "UY.png",
                "continent_id" => 5,
            ],
            [
                "id" => 241,
                "code" => "UZ",
                "continent_code" => "AS",
                "name" => "Uzbekistan",
                "iso3" => "UZB",
                "number" => "860",
                "full_name" => "Republic of Uzbekistan",
                "flag" => "UZ.png",
                "continent_id" => 2,
            ],
            [
                "id" => 242,
                "code" => "VU",
                "continent_code" => "OC",
                "name" => "Vanuatu",
                "iso3" => "VUT",
                "number" => "548",
                "full_name" => "Republic of Vanuatu",
                "flag" => "VU.png",
                "continent_id" => 6,
            ],
            [
                "id" => 243,
                "code" => "VE",
                "continent_code" => "SA",
                "name" => "Venezuela",
                "iso3" => "VEN",
                "number" => "862",
                "full_name" => "Bolivarian Republic of Venezuela",
                "flag" => "VE.png",
                "continent_id" => 5,
            ],
            [
                "id" => 244,
                "code" => "VN",
                "continent_code" => "AS",
                "name" => "Vietnam",
                "iso3" => "VNM",
                "number" => "704",
                "full_name" => "Socialist Republic of Vietnam",
                "flag" => "VN.png",
                "continent_id" => 2,
            ],
            [
                "id" => 245,
                "code" => "WF",
                "continent_code" => "OC",
                "name" => "Wallis and Futuna",
                "iso3" => "WLF",
                "number" => "876",
                "full_name" => "Wallis and Futuna",
                "flag" => "WF.png",
                "continent_id" => 6,
            ],
            [
                "id" => 246,
                "code" => "EH",
                "continent_code" => "AF",
                "name" => "Western Sahara",
                "iso3" => "ESH",
                "number" => "732",
                "full_name" => "Western Sahara",
                "flag" => "EH.png",
                "continent_id" => 1,
            ],
            [
                "id" => 247,
                "code" => "YE",
                "continent_code" => "AS",
                "name" => "Yemen",
                "iso3" => "YEM",
                "number" => "887",
                "full_name" => "Yemen",
                "flag" => "YE.png",
                "continent_id" => 2,
            ],
            [
                "id" => 248,
                "code" => "ZM",
                "continent_code" => "AF",
                "name" => "Zambia",
                "iso3" => "ZMB",
                "number" => "894",
                "full_name" => "Republic of Zambia",
                "flag" => "ZM.png",
                "continent_id" => 1,
            ],
            [
                "id" => 249,
                "code" => "ZW",
                "continent_code" => "AF",
                "name" => "Zimbabwe",
                "iso3" => "ZWE",
                "number" => "716",
                "full_name" => "Republic of Zimbabwe",
                "flag" => "ZW.png",
                "continent_id" => 1,
            ],
        ];
        DB::table('countries')->delete();
        DB::table('countries')->insert($countries);
    }
}
