<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Review;
class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reviews = [
            [
                'name' => 'Alice',
                'date' => 'December 2024',
                'content' => 'Had an amazing time at #propertyname#. The place was just perfect for our family vacation. #hostname# was a great host and made sure everything went smoothly.',
                'rating' => 5,
                'avatar' => 'https://ui-avatars.com/api/?background=random&name=Alice',
                'type' => 'property',
                'created_at' => now(),
                'subject' => 'none',
                'user_id' => 1,
            ],
            [
                'name' => 'David',
                'date' => 'November 2024',
                'content' => 'The location of #propertyname# was unbeatable, and the amenities were top-notch. #hostname# made sure we had everything we needed, and the communication was excellent.',
                'rating' => 4,
                'avatar' => 'https://ui-avatars.com/api/?background=random&name=David',
                'type' => 'property',
                'created_at' => now(),
                'subject' => 'none',
                'user_id' => 1,
            ],
            [
                'name' => 'Sarah',
                'date' => 'October 2024',
                'content' => 'Overall, a good experience. The apartment was nice and clean, though I expected a bit more from the amenities. #hostname# was friendly and tried to make our stay pleasant.',
                'rating' => 4,
                'avatar' => 'https://ui-avatars.com/api/?background=random&name=Sarah',
                'type' => 'host',
                'created_at' => now(),
                'subject' => 'none',
                'user_id' => 2,
            ],
            [
                'name' => 'John',
                'date' => 'September 2024',
                'content' => 'Fantastic getaway! #propertyname# exceeded my expectations. Quiet, relaxing, and everything you could need. #hostname# was very attentive and easy to communicate with.',
                'rating' => 5,
                'avatar' => 'https://ui-avatars.com/api/?background=random&name=John',
                'type' => 'property',
                'created_at' => now(),
                'subject' => 'none',
                'user_id' => 2,
            ],
            // [
            //     'name' => 'Emma',
            //     'date' => 'August 2024',
            //     'content' => 'Lovely stay at #propertyname#. #hostname# was extremely helpful, providing great recommendations. The place itself was cozy, and the surrounding area was perfect for our weekend escape.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Emma',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Michael',
            //     'date' => 'July 2024',
            //     'content' => 'Good value for money. The apartment at #propertyname# was just what we needed for a short stay. #hostname# was very nice and made us feel at home.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Michael',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Laura',
            //     'date' => 'June 2024',
            //     'content' => 'A beautiful place to relax and unwind. #propertyname# was well-maintained and comfortable, and #hostname# ensured we had a stress-free stay.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Laura',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'James',
            //     'date' => 'May 2024',
            //     'content' => 'Perfect spot for a weekend getaway. #propertyname# was lovely, and #hostname# provided great service. Would definitely come back!',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=James',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Olivia',
            //     'date' => 'April 2024',
            //     'content' => 'I had a fantastic experience at #propertyname#. The location was excellent, and the facilities were as expected. #hostname# was welcoming and very helpful.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Olivia',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Ethan',
            //     'date' => 'March 2024',
            //     'content' => 'I enjoyed my stay, although a few minor issues with the property. That said, #hostname# was very quick to address them. The overall stay was still very pleasant.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Ethan',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Sophia',
            //     'date' => 'February 2024',
            //     'content' => 'Absolutely loved #propertyname#! It was so cozy and well-equipped. #hostname# was very accommodating and made our stay so easy and comfortable.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Sophia',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Liam',
            //     'date' => 'January 2024',
            //     'content' => 'Great property and amazing location! #propertyname# had everything we needed. #hostname# was friendly and made sure we felt right at home.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Liam',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Chloe',
            //     'date' => 'December 2023',
            //     'content' => 'The place was very charming and comfortable. #propertyname# offered a great experience for our holiday. #hostname# was helpful throughout our stay.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Chloe',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Benjamin',
            //     'date' => 'November 2023',
            //     'content' => 'Had an excellent stay at #propertyname#. The house was beautiful and had all the amenities we needed. #hostname# was easy to communicate with and very accommodating.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Benjamin',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Mia',
            //     'date' => 'October 2023',
            //     'content' => 'Perfect spot to relax! #propertyname# was cozy and had great views. #hostname# went out of their way to ensure we had a fantastic experience.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Mia',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Noah',
            //     'date' => 'September 2023',
            //     'content' => 'A great stay! The house was very comfortable and clean. #propertyname# was very spacious, and #hostname# was responsive and helpful throughout our visit.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Noah',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Isabella',
            //     'date' => 'August 2023',
            //     'content' => 'Had a lovely time at #propertyname#. The place was very clean, and #hostname# was super accommodating with our requests. Definitely recommend it!',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Isabella',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'William',
            //     'date' => 'July 2023',
            //     'content' => 'We enjoyed our stay at #propertyname#. It was conveniently located and very well-maintained. #hostname# was a great host and made sure we had everything we needed.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=William',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Grace',
            //     'date' => 'June 2023',
            //     'content' => 'A wonderful property to stay at! #propertyname# was cozy and just what we were looking for. #hostname# was friendly and ensured we had a pleasant stay.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Grace',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Lucas',
            //     'date' => 'May 2023',
            //     'content' => 'The place was comfortable and had a lovely vibe. #propertyname# had everything we needed, and #hostname# was easy to reach and very welcoming.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Lucas',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Zoe',
            //     'date' => 'April 2023',
            //     'content' => 'A lovely stay at #propertyname#. It was clean, well-stocked, and had a great atmosphere. #hostname# was super friendly and made sure everything was perfect.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Zoe',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Jack',
            //     'date' => 'March 2023',
            //     'content' => 'Great location and very comfortable. #propertyname# was exactly as described. #hostname# was very welcoming and offered helpful tips for local attractions.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Jack',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Sophia',
            //     'date' => 'February 2023',
            //     'content' => 'Had a great time staying at #propertyname#. It was the perfect place for our group. #hostname# ensured we had everything we needed and made us feel right at home.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Sophia',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'David',
            //     'date' => 'January 2023',
            //     'content' => 'We had a lovely time at #propertyname#. The apartment was spacious and stylish. #hostname# was an excellent host who made sure everything went smoothly.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=David',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Megan',
            //     'date' => 'December 2022',
            //     'content' => 'I had a pleasant stay at #propertyname#. It was just as advertised—cozy, clean, and well located. #hostname# was helpful and communicative throughout our trip.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Megan',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Ella',
            //     'date' => 'November 2022',
            //     'content' => 'This was an ideal spot for a relaxing vacation. #propertyname# was beautiful, and the amenities were perfect. #hostname# made sure we had a stress-free experience.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Ella',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Oliver',
            //     'date' => 'October 2022',
            //     'content' => 'Had an amazing time at #propertyname#. The house was spacious and comfortable, with all the essentials. #hostname# was easy to communicate with and very helpful.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Oliver',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Harper',
            //     'date' => 'September 2022',
            //     'content' => 'Perfect spot for a getaway. #propertyname# was very comfortable, with a great view. #hostname# was a fantastic host and was very responsive to our needs.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Harper',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Amelia',
            //     'date' => 'August 2022',
            //     'content' => 'We had a very pleasant stay at #propertyname#. The place was very clean and stylish. #hostname# ensured that everything was set up for a comfortable stay.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Amelia',
            //     'type' => 'property',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Daniel',
            //     'date' => 'July 2022',
            //     'content' => 'A wonderful experience. #propertyname# was very well kept and had all the necessary amenities. #hostname# was easy to reach and quick to address any questions.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Daniel',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Jackson',
            //     'date' => 'June 2022',
            //     'content' => 'Great experience! #hostname# was very responsive and accommodating. Everything we needed was taken care of, and we felt well-looked after during our stay.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Jackson',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Ava',
            //     'date' => 'May 2022',
            //     'content' => 'Had a lovely time! #hostname# made our stay so much easier by offering local recommendations and making sure we had everything we needed.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Ava',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Mason',
            //     'date' => 'April 2022',
            //     'content' => 'Wonderful experience with #hostname#. The communication was fast, and they went out of their way to ensure we had a comfortable and enjoyable stay.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Mason',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Lily',
            //     'date' => 'March 2022',
            //     'content' => 'Had a great stay. #hostname# was very helpful with check-in and offered great advice on things to do in the area. We appreciated their hospitality!',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Lily',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Eli',
            //     'date' => 'February 2022',
            //     'content' => 'Excellent communication with #hostname#. They were very friendly and made us feel at ease, providing us with useful information to make the most of our stay.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Eli',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Nora',
            //     'date' => 'January 2022',
            //     'content' => 'Had a wonderful experience staying with #hostname#. They were responsive, and any issues we encountered were addressed promptly and professionally.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Nora',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Lucas',
            //     'date' => 'December 2021',
            //     'content' => 'Great host! #hostname# went above and beyond to ensure we had a pleasant stay. They were always available to answer any questions and provide support.',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Lucas',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Grace',
            //     'date' => 'November 2021',
            //     'content' => 'A pleasure to stay with #hostname#. They were kind, easy to communicate with, and always ensured we were comfortable and happy during our stay.',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Grace',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Aiden',
            //     'date' => 'October 2021',
            //     'content' => 'Very smooth experience! #hostname# made sure we had everything we needed and was very responsive. Highly recommend this host!',
            //     'rating' => 4,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Aiden',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ],
            // [
            //     'name' => 'Ella',
            //     'date' => 'September 2021',
            //     'content' => '#hostname# was wonderful to work with. They were thoughtful and helpful, ensuring we had a great time during our stay. I would definitely return!',
            //     'rating' => 5,
            //     'avatar' => 'https://ui-avatars.com/api/?background=random&name=Ella',
            //     'type' => 'host',
            //     'created_at' => now(),
            //     'subject' => 'none',
            //     'user_id' => 1,
            // ]
        ];
        $this->command->info('Seeding reviews...');
        Review::insert($reviews);
        $this->command->info('Done seeding reviews!');
        $this->command->info('===========================================');
    }
}
